# Generated by Django 5.0.7 on 2024-12-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tictactoeresult',
            name='new_field',
        ),
    ]
