# Generated by Django 5.0.7 on 2024-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_tictactoeresult_new_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoeresult',
            name='difficulty_level',
            field=models.CharField(max_length=12),
        ),
    ]
