# Generated by Django 5.0.7 on 2024-12-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_tictactoeresult_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedianIncomeByAgeConstantDollars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('demographic_age', models.TextField(blank=True, null=True)),
                ('yearly_value_constant_dollars', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'median_income_by_age_constant_dollars',
                'managed': False,
            },
        ),
    ]
