# Generated by Django 5.0.7 on 2024-12-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_medianincomebyageconstantdollars'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedianIncomePercentChangeByAgeConstantDollars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('demographic_age', models.TextField(blank=True, null=True)),
                ('starting_value_constant_dollars', models.FloatField(blank=True, null=True)),
                ('ending_value_constant_dollars', models.FloatField(blank=True, null=True)),
                ('percent_change_in_income', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'median_income_percent_change_by_age_constant_dollars',
                'managed': False,
            },
        ),
    ]
