FROM python:3.11-slim

WORKDIR opt/django/
#COPY pyproject.toml .
COPY requirements.txt .
COPY ./portfolio/ ./portfolio/
#RUN python -m pip install . -I --no-cache-dir
RUN pip install -r requirements.txt -I --no-cache

WORKDIR portfolio/
RUN chmod +x start.sh

EXPOSE 8000
CMD ["./start.sh"]
