FROM python:3.11-slim

WORKDIR /opt/django/

COPY pyproject.toml .
COPY ./portfolio/ ./portfolio/
COPY ./portfoliopython/ ./portfoliopython/
COPY ./docker/entrypoint.sh .

RUN chmod +x /opt/django/portfolio/start.sh
RUN chmod +x /opt/django/entrypoint.sh

RUN python -m pip install . 

EXPOSE 8000

WORKDIR /opt/django/
CMD ["/opt/django/entrypoint.sh"]

WORKDIR portfolio/